name:               'allnetwork-web'
version:            '0.1.1'
env:                'dev'
basePath:           ''
srcPath:            'src'
templateExtension:  'php'
cache:              false
usePropel:          true
useTwig:            true
response:           'html'
